<a href="https://colab.research.google.com/github/jasen8651/spring011/blob/master/python3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#3차원 이상에서 차원 구분법
import numpy as np
#print하면 array글자는 안보인다. 공백이 그대로 보인다. -> 차원구분가능
b = np.arange(24).reshape(2,3,4)
print(b)

b[1,2]

b[0,1]

b[0,1,3]

b[0]

b[[0],:,:]
#b의 0번째 공간 1번재 행 미만, 열 전체
b[0,:1,:]

#ellipsis 모든것을 의미
b[0,:1,:]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[0, 1, 2, 3]])

In [ ]:

#ellipsis 모든것을 의미
b[0,...] 
b[0,:,:] 

b[0, : , 1]
b[0,...]



b = np.arange(24).reshape(2,3,4)
print(b)
b[0,:,[1,3]]

#숫자 4,5,6,7,,16,17,18,19 가져오기
b[:,1:2,:]
print("----------------")
#3,7,11,15,1923
b[:,:,3:4]
b[:,:,-1]
b[:,:,[3]]

print("----------------")


In [34]:
np.arange(100000)
# ...: 데이터 수가 많아 단순히 줄임 표현// ellipsis : 전체

np.set_printoptions(edgeitems=6)
np.arange(100000)

a =np.arange(12).reshape(3,4)
a
a.shape

b =np.arange(1,13).reshape(3,4)
b
b.shape

a +b 

#numpy는 elementwise로 vectorize(데이터의 연산을 일괄적으로 처리 가능)로 연산을 한다.

# 파이썬에서 list에서 +는 list를 확장시킴
#[1,2,3]+[4,5]

@np.vectorize
def plus(a,b):
  return a+b
plus([1,2,3],[4,5,6])

array([5, 7, 9])

In [46]:
@np.vectorize
def plus(a,b):
  return a+b
plus([1,2,3],[4,5,6]) #elementwise vectroize

# *
type(np.array(3))
c = np.matrix([[1,2],[3,4]])
c
type(c)

#np에서는 ndarray이외에 matrix라는 자료형 존재, 곱하기를 뜻함
c*c #행열곱
#ndarray : 행렬곱 연산자 @이다. 
a.shape

#a @ b
#행렬곱을 하기위해서 shape가 맞아야함


(3, 4)

In [47]:
b.shape


(3, 4)

In [49]:
a

a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [51]:
a @ a.T

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [58]:
np.dot(a, a.T)
a.dot(a.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [ ]:
#broadcasting : 파이썬 배열과 숫자간의 연산 가능 , 모양이 안맞아도 특정한 조건에 맞으면 모양을 같게 만들어 연사하는 기능
# 안되는 경우 : 
#a + np.array([3,4])

a + np.array([[1],[2]])

In [4]:
# stries : 다음 원소끼리 메모리 크기를 차원별로 알려준다,., c의 포인터개념을 알고있으면 이해 쉬움
a.strides
a.dtype
#행의 메모리 간격은 32바이트 
#열의 메모리 간격은 4바이트
#열의 원소 갯수 * itemsize = 행의 메모리 간격
#itemsize = 열의 메모리 간격
a.shape


#axis : 디차원 배열을 연산할때 기준이되는 축이다. 
a
np.sum(a)#2는 2차원 배열이므로 axis는 0은 행기준
np.sum(a, axis=0)

#3차원에서도 사용가능
a = np.arange(24).reshape(2,3,4)
np.sum(a, axis =0)# 공간마다가준

np.sum(a, axis=1)

#a.sum(axis=2)
a.sum(axis=2) #열기준
#3차원은 행렬에 공간 개념이 추가
#2차원(axis=0, axis=1)(행,열)
#3차원(axis=0, axis=1, axis=2)(공간,행,열)

#array모양 바꾸기
#reshape : 차원을 바꿔주는 기능을 하낟.
a = np.arange(24).reshape(3,8) # 
a
b = a.reshape(3,8)
a #reshape수행후 원래의 값은 그대로 있다,

a.reshape(2,3, 4)
#a.reshape(2,3, 5)# 맞지 않음

a.reshape(2,3, -1 )

#a.reshape(3,5, -1) :

# 음수 2개를 사용 불가
#a.reshape(3,-1, -1)

#2차원
a = np.arange(6).reshape(2,3)
a

#3차원
a = np.arange(6).reshape(2,3,1)
a


# size 원소의 갯수 
a = np.arange(24)
print(a.size)

np.resize(a,(2,3,1))
#빈공간은 0으로 채워줌
b=np.arange(24)
b.resize((2,3,8))
b





NameError: ignored

In [12]:
#배열 쪼개기
a = np.arange(24)
a= np.split(a, 2, axis=0)
a



[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [14]:
print(type(a))
print(type(a[0]))

b = np.arange(24)
b= np.split(b, 2)
b


<class 'list'>
<class 'numpy.ndarray'>


[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [18]:
print(type(b))
print(type(b[1]))
print(b[1])
print(b[1][2])


<class 'list'>
<class 'numpy.ndarray'>
[12 13 14 15 16 17 18 19 20 21 22 23]
14


In [22]:
c = np.array(b)
c
print(type(c))
print(c)
print(c[1,2])

<class 'numpy.ndarray'>
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
14


In [23]:
#split은 axis파라미터가 있다. default =axis=0
a = np.arange(24)
b =a.reshape(4,6)
print(b)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [24]:
np.split(b,2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [28]:
np.split(b,2, axis=1)

np.hsplit(a,2)
np.vsplit(b,2) #수직

np.hsplit(b,2)#수평

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [33]:
#indices_or_sections : split 시리즈 함수들의 2번쩨 파라미터 이름이 indices_or_sections이다, 숫자를 묶어 넣으면 구간으로 쪼개진다.
a = np.arange(24)
a
#처럼부터 ~2미만 : [0,1]
#2부터 3미만 [2]
#3부터 끝까지 [3,4,5...]
np.hsplit(a,(2,3))


[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

In [34]:
#3부터 8미만까지 [3,4,5,6,7]
#8부터 끝까지[8,9,10...]
np.hsplit(a,(2,3,8))

[array([0, 1]),
 array([2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [38]:
#배열 합치기
a = np.arange(24)
x,y,z = np.split(a,3)

print(x)
print(y)
print(z)

#hstack : 수평 합치기 
np.hstack((x,y))
#vstack : 세로 합치기
np.vstack((x,y))


#DSTACK : 합쳐서 3차원으로 만들어줌 
print(x)
print(y)



[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]
[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [42]:
c =np.dstack((x,y)) # (1,8,2)
c

c.shape

#contcatnate asis반향에 그대로 합칩
a = np.arange(12).reshape(3,4)
x,y =np.split(a,2, axis=1)

print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [51]:
#차원확장
#1차원             #2차원
a = np.arange(12).reshape(3,4)
a
#3차원으로 확장, 튜플에서 원소가 1개만 있으면 차원만 확장
np.stack((a,))

#newaxis : 인덱싱할떼 사용하면 차원을 늘릴수있다.
a[np.newaxis].shape

a[:,np.newaxis,:]

a[:,:,np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [63]:
a[:,:,np.newaxis].shape

#newaxis대신에 none을 사용해도 됨 none는 직곽전이지 않고 ㅎ헤갈려서 np.newaxis를 만금

np.expand_dims(a,0)

a[np.newaxis,:,:]

np.expand_dims(a, 1)
np.expand_dims(a,2)

#array 한줄 펴기
a = np.arange(12).reshape(3,4)
a
#flatten():는 결과를 리턴하고 메모리의 값은 변경되지 않는다.
b =a.flatten()
b
#서로 차원교환
np.swapaxes

a= np.array([[1],[2]])
a
# a의 0번 차원과 1번 차원을 서로 바꿈
a.reshape
b =np.swapaxes(a,1,0)
b


array([[1, 2]])